Repository kkrt-labs/kakarot-rpc, pull requests merged in 2023-08, with the labels that each got.

#421 feat: update benchmarking workflow to only run `push`
  .github/workflows/benchmark.yml
Labels: skip-changelog

#403 feat: implement the eth filter methods as todo!
  crates/eth-rpc/src/api/eth_api.rs
  crates/eth-rpc/src/servers/eth_rpc.rs
Labels: skip-changelog

#432 fix: add dependencies as skip-label to not fail dependabot CI job
  .github/workflows/changelog.yml
Labels: dependencies

#434 feat: receipt wrapper
  CHANGELOG.md
  crates/core/src/client/mod.rs
  crates/core/src/models/convertible.rs
  crates/core/src/models/event_filter.rs
  crates/core/src/models/mod.rs
  crates/core/src/models/test_data/conversion/eth/transaction_receipt.json
  crates/core/src/models/test_data/conversion/starknet/transaction_receipt.json
  crates/core/src/models/transaction_receipt.rs
Labels: enhancement

#452 ci: add nextest in CI
  .github/workflows/test.yml
  Makefile
Labels: skip-changelog

#466 dev: bump reth
  Cargo.lock
  Cargo.toml
  Dockerfile
  crates/core/src/client/helpers.rs
  crates/core/src/client/mod.rs
  crates/core/src/client/tests/mod.rs
  crates/core/src/mock/assert_helpers.rs
  crates/core/src/models/block.rs
  crates/core/src/models/event_filter.rs
  crates/core/src/models/signature.rs
  crates/core/src/models/test_data/conversion/eth/transaction_receipt.json
  crates/core/src/models/transaction.rs
  crates/core/src/models/transaction_receipt.rs
  crates/core/tests/client.rs
  crates/eth-rpc/src/api/eth_api.rs
  crates/eth-rpc/src/servers/eth_rpc.rs
  docker-compose.yaml
Labels: skip-changelog

#473 dev: add sysroot
  Dockerfile
Labels: skip-changelog
